spring:
  main:
    banner-mode: "off"

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true

rsa:
  private-key: classpath:private.pem
  public-key: classpath:public.pem